psproject/psapp/urls.py
from django.urls import path
from .import views
app_name='psapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

psproject/psproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from psproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("psapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                         document_root =settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

psproject/psapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

psproject/psapp/forms.py
from django import forms
from.models import Movie
class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

psproject/psapp/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)

def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})

def add_movie(request):
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('psapp:index')
    else:
        form = MovieForm()
    return render(request, 'add.html', {'form': form})

def update(request, id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('psapp:index')
    else:
        form = MovieForm(instance=movie)
    return render(request, 'edit.html', {'form': form, 'movie': movie})

def delete(request, id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST":
        movie.delete()
        return redirect('psapp:index')
    return render(request, 'delete.html', {'movie': movie})

psproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
   <input type="text" name="name" placeholder="Enter your movie name">
   <input type="text" name="desc" placeholder="Enter your movie description">
   <input type="text" name="year" placeholder="Enter your movie year">
   <input type="file" name="img">
   <input type="submit" value="Submit">
</form>
{% endblock %}

psproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie store
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

psproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you want to delete this Movie?
  <input type="submit" value="submit">
</form>

psproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class=" col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>

<div class="col-md-6">
    <h2>{{movie.name}}</h2>
    <h4>{{movie.desc}}</h4>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning " href="{% url 'psapp:update' movie.id %}"> update </a>
        <a class="btn btn-danger" href="{% url 'psapp:delete' movie.id %}"> delete </a>
</div>

   </div>
</div>

{% endblock %}

psproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

psproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row movie-card-container">
        {% for i in movie_list %}
        <div class="col-md-3" style="width: 18rem; border: 1px solid black; padding: 10px; margin-bottom: 10px; margin-left: 10px;">
            <div class="card movie-card">
                <img src="{{ i.img.url }}" class="card-img-top" alt="" style="height: 250px;">
                <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p class="card-text">{{ i.desc }}</p>
                    <a href="{% url 'psapp:detail' i.id %}" class="btn btn-primary">View details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<div style="text-align: center; margin-top: 20px;">
    <form action="{% url 'psapp:add_movie' %}" method="GET">
        <input type="submit" value="Add" class="btn btn-primary">
    </form>
</div>
{% endblock %}